# Generated by Django 6.0.1 on 2026-05-16 09:16

import billing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('bookings', '0013_remove_court_secondary_closing_time_and_more'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Revenue', 'verbose_name_plural': 'Revenues'},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate a customer without deleting records.', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is this a recurring/monthly expense?', verbose_name='Recurring'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_note',
            field=models.CharField(blank=True, help_text='E.g., "Monthly rent", "Weekly electricity bill".', max_length=100, verbose_name='Recurrence Note'),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Billing customer associated with this revenue entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='billing.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Mark this revenue entry as verified/reconciled.', verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='receipt_number',
            field=models.CharField(default=billing.models._generate_receipt_number, editable=False, help_text='Auto-generated unique receipt reference.', max_length=20, unique=True, verbose_name='Receipt Number'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Link to a registered user account, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Linked User'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (₹)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('SALARIES', 'Salaries'), ('EQUIPMENT', 'Equipment'), ('RENT', 'Rent'), ('MARKETING', 'Marketing'), ('INSURANCE', 'Insurance'), ('TAXES', 'Taxes'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (₹)'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='bookings.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('ONLINE', 'Online'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'is_active'], name='bill_cust_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'name'], name='bill_cust_tenant_name_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'date'], name='bill_expense_tenant_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'category'], name='bill_expense_category_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['tenant', 'date'], name='bill_revenue_tenant_date_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['tenant', 'payment_method'], name='billing_revenue_pm_idx'),
        ),
    ]
