# Generated by Django 6.0.4 on 2026-04-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_payment_method'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('tenant', 'name')},
        ),
    ]
