# Generated by Django 6.0.4 on 2026-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='secondary_closing_time',
            field=models.TimeField(blank=True, help_text='e.g., 22:00 for evening shift', null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='secondary_opening_time',
            field=models.TimeField(blank=True, help_text='e.g., 16:00 for evening shift', null=True),
        ),
    ]
