# Generated by Django 6.0.4 on 2026-04-24 05:25

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_unique_booking_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='peak_hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price during peak hours', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='size',
            field=models.CharField(blank=True, help_text='e.g., 100x60 ft', max_length=50),
        ),
        migrations.AddField(
            model_name='court',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='court',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='sport_type',
            field=models.CharField(choices=[('CRICKET', 'Cricket'), ('FOOTBALL', 'Football'), ('BADMINTON', 'Badminton'), ('TENNIS', 'Tennis'), ('BASKETBALL', 'Basketball'), ('VOLLEYBALL', 'Volleyball'), ('SQUASH', 'Squash'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
