# Generated by Django 6.0.4 on 2026-04-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_unique_court_name_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='image',
            field=models.ImageField(blank=True, help_text='Court photo', null=True, upload_to='courts/'),
        ),
    ]
