# Generated by Django 6.0.4 on 2026-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_court_secondary_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='secondary_closing_time',
        ),
        migrations.RemoveField(
            model_name='court',
            name='secondary_opening_time',
        ),
        migrations.AddField(
            model_name='court',
            name='additional_shifts',
            field=models.JSONField(blank=True, default=list, help_text='[{"start_time": "16:00", "end_time": "22:00"}]', null=True),
        ),
    ]
