# Generated by Django 6.0.4 on 2026-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_court_additional_shifts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='secondary_closing_time',
        ),
        migrations.RemoveField(
            model_name='court',
            name='secondary_opening_time',
        ),
        migrations.AddField(
            model_name='court',
            name='operating_hours',
            field=models.JSONField(blank=True, default=list, help_text="List of timing shifts: [{'start': '06:00', 'end': '10:00'}, ...]"),
        ),
    ]
